on:
  push:
    branches:
    - main
  workflow_dispatch:
jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        yocto_version: ['mickledore'] #, 'scarthgap']
    steps:
      - uses: actions/checkout@v4
        with:
          path: '.'
      - name: build
        run: |
          ls .
          pwd
          ls ../
          ls /home/runner/work/meta-find-program/meta-find-program/meta-find-program
          ls /home/runner/work/meta-find-program/meta-find-program/
          ls /home/runner/work/meta-find-program/
          ls /home/runner/work/
          # apt update && apt install -y gawk wget git-core diffstat unzip texinfo \
          # gcc-multilib build-essential chrpath socat file cpio python3 \
          # python3-pip python3-pexpect python3-venv xz-utils debianutils iputils-ping \
          # libsdl1.2-dev xterm tar locales rsync vim curl zstd \
          # liblz4-tool libssl-dev bc lzop libgnutls28-dev git-lfs \
          # python-is-python3 python3-passlib
          # git clone -b ${{ matrix.yocto_version }} --single-branch git://git.yoctoproject.org/poky
          # git clone -b $YOCTO_BRANCH --single-branch git://git.openembedded.org/meta-openembedded
          # cd ../
          # . ./poky/oe-init-build-env
          # bitbake-layers add-layer ../meta-openembedded/meta-oe/

        
    
