on:
  push:
    branches:
    - main
  workflow_dispatch:
jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-22.04
    steps:
      - name: echo
        run: |
          echo "hello"
          cat /etc/os-release
        
    
